economy:
  worth_per_block: 0.01
  random_payout: false
  on_block_break: true
  on_block_place: true
  pay_after_blocks: 1
  chanced_payout: false
  percent_chance_to_pay: 10.0
lang:
  message_on_pay: false
  message: '&2You received &f%money%&2.'
blacklist:
  use: true
  use_as_whitelist: false
  blocks:
    - LONG_GRASS
    - YELLOW_FLOWER
    - RED_ROSE
internal:
  debug: false
